### ISSUE TITLE
I want study with u,gulp can't run

### ISSUE THREAD

**Issue by superchangme** [airen/jsStudy#4]
H:\work\github\jsStudy>gulp
[23:49:05] Requiring external module babel-core/register
module.js:597
  return process.dlopen(module, path._makeLong(filename));

when i run gulp after npm install ,it breaks,how can i do?

**Comment by superchangme** [comment]
![image](https://cloud.githubusercontent.com/assets/7008154/20867310/949d4e60-ba7c-11e6-8497-d0b73bededd3.png)

**Comment by airen** [comment]
#6
