### ISSUE TITLE
gulp启动失败呢

### ISSUE THREAD

**Issue by CodeDreamfy** [airen/jsStudy#6]
![image](https://cloud.githubusercontent.com/assets/7604937/21674293/f7280e54-d367-11e6-926f-d0933b8a6f7d.png)

**Comment by desperadoray** [comment]
I got the same issue

**Comment by Mcbai** [comment]
看错误提示，上面显示缺少babel-core/reister模块，把缺少的全下下来就行，npm install xxx --save-dev
另外在git bash里运行，感觉怪怪的，cmd感觉操作起来更方便，当然看你们自己习惯

**Comment by Annkeke** [comment]
这个我试了，我再试下T-T。谢谢

**Comment by Annkeke** [comment]
![1490758740 1](https://cloud.githubusercontent.com/assets/13724803/24437543/399d6552-1474-11e7-955e-41c7ef1c949b.png)
可以再解答一下吗，看不懂是我的版本什么问题吗

**Comment by u14e** [comment]
我也遇到同样的问题，我把gulpfile.babel.js里面的uc版本从`and_uc 9.9`改成`last 1 and_uc version`就可以了
<img width="255" alt="_20170403171746" src="https://cloud.githubusercontent.com/assets/14119121/24603429/55bd3e74-1893-11e7-84d2-204e72cc6d04.png">

参考链接：[Unknown version 9.9 of and_uc](https://github.com/postcss/autoprefixer/issues/746)

**Comment by Annkeke** [comment]
我把gulpfile.babel.js里面的uc版本从and_uc 9.9改成last 1 and_uc version就可以了，谢谢U14e.666
